<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInita8ac5b33f2e6d3c5b711c0f5eb01902d
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Bluehost\Plugin\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Bluehost\Plugin\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInita8ac5b33f2e6d3c5b711c0f5eb01902d', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Bluehost\Plugin\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInita8ac5b33f2e6d3c5b711c0f5eb01902d', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Bluehost\Plugin\Composer\Autoload\ComposerStaticInita8ac5b33f2e6d3c5b711c0f5eb01902d::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
